using System;
using System.Collections.Generic;
using CluedIn.Core.Data;
using CluedIn.Core.Net.Mail;
using CluedIn.Core.Providers;

namespace CluedIn.Crawling.Sterling.Core
{
    public class SterlingConstants
    {
        public struct KeyName
        {
            public const string ApiKey = nameof(ApiKey);
            public const string CandidateIds = nameof(CandidateIds);
            public const string IdentifyVerificationIds = nameof(IdentifyVerificationIds);
        }

        public const string Candidate = "/Candidate";
        public const string Screening = "/Screening";

        // TODO Complete the following section
        // Please see https://cluedin-io.github.io/CluedIn.Documentation/docs/1-Integration/build-integration.html
        public const string CrawlerDescription = "Sterling is a candidate background-check manager";
        public const string Instructions = "Provide authentication instructions here, if applicable";
        public const IntegrationType Type = IntegrationType.Cloud;
        public const string Uri = "https://www.sterlingcheck.com/"; //Uri of remote tool if applicable

        // To change the icon see embedded resource
        // src\Sterling.Provider\Resources\cluedin.png
        public const string IconResourceName = "Resources.sterling.png";

        public static IList<string> ServiceType = new List<string> { "" };
        public static IList<string> Aliases = new List<string> { "" };
        public const string Category = "";
        public const string Details = "";
        public static AuthMethods AuthMethods = new AuthMethods()
        {
            token = new Control[]
            {
                new Control()
                {
                    displayName = "API key",
                    isRequired = false,
                    name = "ApiKey",
                    type = "text"
                }
            }
        };


        public const bool SupportsConfiguration = true;
        public const bool SupportsWebHooks = false;
        public const bool SupportsAutomaticWebhookCreation = true;

        public const bool RequiresAppInstall = false;
        public const string AppInstallUrl = null;
        public const string ReAuthEndpoint = null;

        #region Autogenerated constants
        public const string CodeOrigin = "Sterling";
        public const string ProviderRootCodeValue = "Sterling";
        public const string CrawlerName = "SterlingCrawler";
        public const string CrawlerComponentName = "SterlingCrawler";
        public static readonly Guid ProviderId = Guid.Parse("ed9b29b1-f4c7-42ca-b4a9-bd325c775f0a");
        public const string ProviderName = "Sterling";

        public static readonly ComponentEmailDetails ComponentEmailDetails = new ComponentEmailDetails
        {
            Features = new Dictionary<string, string>
            {
                                       { "Tracking",        "Expenses and Invoices against customers" },
                                       { "Intelligence",    "Aggregate types of invoices and expenses against customers and companies." }
                                   },
            Icon = ProviderIconFactory.CreateConnectorUri(ProviderId),
            ProviderName = ProviderName,
            ProviderId = ProviderId,
            Webhooks = SupportsWebHooks
        };

   

        public static IProviderMetadata CreateProviderMetadata()
        {
            return new ProviderMetadata
            {
                Id = ProviderId,
                ComponentName = CrawlerName,
                Name = ProviderName,
                Type = Type.ToString(),
                SupportsConfiguration = SupportsConfiguration,
                SupportsWebHooks = SupportsWebHooks,
                SupportsAutomaticWebhookCreation = SupportsAutomaticWebhookCreation,
                RequiresAppInstall = RequiresAppInstall,
                AppInstallUrl = AppInstallUrl,
                ReAuthEndpoint = ReAuthEndpoint,
                ComponentEmailDetails = ComponentEmailDetails
            };
        }
        #endregion
    }
}
